name: fastscape-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - xarray
  - xarray-simlab=0.3.0
  - fastscapelib-f2py=2.8.1
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - graphviz
  - python-graphviz
  - numba
  - pyvista
  - itkwidgets
  - ipywidgets
  - hvplot
  - datashader
  - pip
  - pip:
      - git+https://github.com/fastscape-lem/fastscape
